Baseball/Controllers/ChampionShipController.cs
using Baseball.Common.ViewModels.ChampionShipViewModels;
using Baseball.Core.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using static Baseball.Common.RoleConstants;

namespace Baseball.Controllers
{
    [Authorize]
    public class ChampionShipController : Controller
    {
        private readonly IChampionShipService championShipService;
        private readonly ILogger logger;

        public ChampionShipController(IChampionShipService championShipService, ILogger<ChampionShipController> logger)
        {
            this.championShipService = championShipService;
            this.logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> All()
        {
            try
            {
                var championShips = await championShipService.GetAllAsync();
                return View(championShips);
            }
            catch (Exception ex)
            {
                logger.LogError(nameof(All), ex.Message);
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpGet]
        public async Task<IActionResult> GetDetails(int id)
        {
            try
            {
                var championShipDetails = await championShipService.GetDetailsAsync(id);
                return View(championShipDetails);
            }
            catch(ArgumentNullException ae)
            {
                logger.LogError(nameof(GetDetails), ae.Message);
                return RedirectToAction(nameof(All));
            }
            catch (Exception e)
            {
                logger.LogError(nameof(GetDetails), e.Message);
                return RedirectToAction(nameof(All));
            }
        }

        [HttpGet]
        [Authorize(Roles = $"{CoachRoleName}, {PlayerRoleName}")]
        public IActionResult Add()
        {
            var championShip = new AddChampionShipViewModel();
            return View(championShip);
        }

        [HttpPost]
        [Authorize(Roles = $"{CoachRoleName}, {PlayerRoleName}")]
        public async Task<IActionResult> Add(AddChampionShipViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                await championShipService.AddAsync(model);
                return RedirectToAction(nameof(All));
            }
            catch (Exception e)
            {
                logger.LogError(nameof(Add), e.Message);
                ModelState.AddModelError("", $"Something went wrong. Champion ship was not added. Please try again.");
                return View(model);
            }
        }

        [HttpGet]
        [Authorize(Roles = $"{CoachRoleName}, {PlayerRoleName}")]
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var championShip = await championShipService.GetByIdAsync(id);
                if (championShip is null)
                {
                    return RedirectToAction(nameof(All));
                }

                return View(championShip);
            }
            catch (Exception e)
            {
                logger.LogError(nameof(Edit), e.Message);
                return RedirectToAction(nameof(All));
            }
        }

        [HttpPost]
        [Authorize(Roles = $"{CoachRoleName}, {PlayerRoleName}")]
        public async Task<IActionResult> Edit(int id, EditChampionShipViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (id != model.Id)
            {
                return View(model);
            }

            try
            {
                await championShipService.UpdateAsync(id, model);
                return RedirectToAction(nameof(All));
            }
            catch(ArgumentNullException ne)
            {
                logger.LogError(nameof(Edit), ne.Message);
                return RedirectToAction(nameof(All));
            }
            catch (Exception e)
            {
                logger.LogError(nameof(Edit), e.Message);
                return RedirectToAction(nameof(All));
            }
        }

        [HttpPost]
        [Authorize(Roles = $"{CoachRoleName}, {PlayerRoleName}")]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await championShipService.DeleteAsync(id);
                return RedirectToAction(nameof(All));
            }
            catch(ArgumentNullException ne)
            {
                logger.LogError(nameof(Delete), ne.Message);
                return RedirectToAction(nameof(All));
            }
            catch (Exception e)
            {
                logger.LogError(nameof(Delete), e.Message);
                return RedirectToAction(nameof(All));
            }
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> GetHomePageAll()
        {
            try
            {
                var championShips = await championShipService.GetHomePageAllAsync();
                return View(championShips);
            }
            catch (Exception e)
            {
                logger.LogError(nameof(GetHomePageAll), e.Message);
                return View("Unreachable");
            }
        }
    }
}

Baseball/Views/ChampionShip/Add.cshtml
@model AddChampionShipViewModel

@{
    ViewBag.Title = "Add ChampionShip";
}


<h2 class="text-center">@ViewBag.Title</h2>

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form asp-action="Add" method="post">
            <div class="mb-3">
                <label asp-for="@Model.Name" class="form-label">Team Name</label>
                <input asp-for="@Model.Name" class="form-control" aria-required="true" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Year" class="form-label">Year</label>
                <input asp-for="@Model.Year" class="form-control" aria-required="true" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <input class="btn btn-primary" type="submit" value="Add" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Baseball/Views/ChampionShip/All.cshtml
@model List<ChampionShipViewModel>

@{
    ViewBag.Title = "All Championships";
}

<h2 class="text-center">@ViewBag.Title</h2>
@if (User.IsInRole($"{CoachRoleName}") || User.IsInRole($"{PlayerRoleName}"))
{
    <a class="fs-6 btn btn-success mb-3 p-2" asp-area="" asp-controller="ChampionShip" asp-action="Add">Add Championship</a>
}

<table class="table">
    <thead class="thead-light">
        <tr>
            <th scope="col">Championship</th>
            <th scope="col"></th>
            @if (User.IsInRole($"{CoachRoleName}") || User.IsInRole($"{PlayerRoleName}"))
            {
                <th scope="col"></th>
                <th scope="col"></th>
            }
        </tr>
    </thead>
    <tbody>
        @foreach (var championShip in Model)
        {
            <tr>
                <td>@championShip.Name  - @championShip.Year</td>
                <td>
                    <a class="fs-6 btn btn-success mb-3 p-2" asp-area="" asp-controller="ChampionShip" asp-action="GetDetails" asp-route-id="@championShip.Id">Details</a>
                </td>
                @if (User.IsInRole($"{CoachRoleName}") || User.IsInRole($"{PlayerRoleName}"))
                {
                    <td>
                        <a class="fs-6 btn btn-success mb-3 p-2" asp-area="" asp-controller="ChampionShip" asp-action="Edit" asp-route-id="@championShip.Id">Edit</a>
                    </td>
                    <td>
                        <form class="input-group-sm" asp-controller="ChampionShip" asp-action="Delete" asp-route-id="@championShip.Id">
                            <input class="fs-6 btn btn-danger mb-3 p-2" type="submit" value="Delete" />
                        </form>
                    </td>
                }
            </tr>
        }
    </tbody>
</table>

Baseball/Views/ChampionShip/Edit.cshtml
@model EditChampionShipViewModel

@{
    ViewBag.Title = "Update Championship";
}


<h2 class="text-center">@ViewBag.Title</h2>

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form asp-action="Edit" method="post">
            <div class="mb-3">
                <label asp-for="@Model.Name" class="form-label">Team Name</label>
                <input asp-for="@Model.Name" class="form-control" aria-required="true" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Year" class="form-label">Year</label>
                <input asp-for="@Model.Year" class="form-control" aria-required="true" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
             <form class="input-group-sm" asp-controller="Teeam" asp-action="Edit" asp-route-bookId="@Model.Id">
                <input type="submit" value="Update" class="fs-6 btn btn-success mb-3 p-2" />
            </form>
        </form>
    </div>
</div>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Baseball/Views/ChampionShip/GetDetails.cshtml
@model ChampionShipDetailsViewModel

@{
    ViewBag.Title = @Model.Name;
}

<h2 class="text-center">@ViewBag.Title</h2>

@if (Model.Teams.Any())
{
    <table class="table">
        <thead class="thead-light">
            <tr>
                <th scope="col"><h5>Rank</h5></th>
                <th scope="col"><h5>Team</h5></th>
                <th scope="col"><h5>Wins</h5></th>
                <th scope="col"><h5>Loses</h5></th>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.Teams.Count; i++)
            {
                <tr>
                    <td>@(i + 1)</td>
                    <td>@Model.Teams[i].Name</td>
                    <td>@Model.Teams[i].WinGames</td>
                    <td>@Model.Teams[i].LoseGames</td>
                </tr>
            }
        </tbody>
    </table>
}

@if (Model.Games.Any())
{
    <h3 class="text-center">Games</h3>

    <partial name="_GamePartial" model="@Model.Games" />
}

@if (!Model.Teams.Any() && !Model.Games.Any())
{
    <h6 class="text-center">No information is added for this championship</h6>
}

Baseball/Views/ChampionShip/GetHomePageAll.cshtml
@model List<HomePageViewModel>

@{
    ViewBag.Title = "Welcome to Baseball Statistics";
}

<h2 class="text-center">@ViewBag.Title</h2>

@foreach (var championShip in Model)
{

    @if (championShip.Teams.Any())
    {
        <h4 class="text-center">@championShip.ChampionShipName - @championShip.ChampionShipYear</h4>

        <table class="table">
            <thead class="thead-light">
                <tr>
                    <th scope="col"><h5>Rank</h5></th>
                    <th scope="col"><h5>Team</h5></th>
                    <th scope="col"><h5>Wins</h5></th>
                    <th scope="col"><H5>Loses</H5></th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < championShip.Teams.Count; i++)
                {
                    <tr>
                        <td>@(i + 1)</td>
                        <td>@championShip.Teams[i].Name</td>
                        <td>@championShip.Teams[i].WinGames</td>
                        <td>@championShip.Teams[i].LoseGames</td>
                    </tr>
                }
            </tbody>
        </table>
    }
}

Baseball/Views/ChampionShip/Unreachable.cshtml
<h5>Our application is temporary unreachable. Please try again later</h5>