Baseball/Controllers/BatController.cs
using Baseball.Common.ViewModels.BatViewModels;
using Baseball.Core.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using static Baseball.Common.RoleConstants;

namespace Baseball.Controllers
{
    [Authorize]
    public class BatController : Controller
    {
        private readonly IBatService batService;
        private readonly IBatMaterialService batMaterialService;
        private readonly ILogger logger;


        public BatController(IBatService batService, IBatMaterialService batMaterialService, ILogger<BatController> logger)
        {
            this.batService = batService;
            this.batMaterialService = batMaterialService;
            this.logger = logger;
        }

        [HttpGet]
        public async Task<IActionResult> All()
        {
            try
            {
                var bats = await batService.GetAllAsync();
                return View(bats);
            }
            catch (Exception ex)
            {
                logger.LogError(nameof(All), ex.Message);
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpGet]
        [Authorize(Roles = $"{CoachRoleName}, {PlayerRoleName}")]
        public async Task<IActionResult> Add()
        {
            var model = new AddBatViewModel()
            {
                Materials = (await batMaterialService.GetAllBatMaterialsAsync()).ToList()
            };

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = $"{CoachRoleName}, {PlayerRoleName}")]
        public async Task<IActionResult> Add(AddBatViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                await batService.AddAsync(model);
                return RedirectToAction(nameof(All));
            }
            catch (Exception ex)
            {
                logger.LogError(nameof(Add), ex.Message);
                ModelState.AddModelError("", $"Something went wrong. The bat was not added. Please try again.");
                return View(model);
            };
        }

        [HttpGet]
        [Authorize(Roles = $"{CoachRoleName}, {PlayerRoleName}")]
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var model = await batService.GetByIdAsync(id);
                return View(model);
            }
            catch (ArgumentException ae)
            {
                logger.LogError(nameof(Edit), ae.Message);
                return RedirectToAction(nameof(All));
            }
            catch (Exception e)
            {
                logger.LogError(nameof(Edit), e.Message);
                return RedirectToAction(nameof(All));
            }
        }

        [HttpPost]
        [Authorize(Roles = $"{CoachRoleName}, {PlayerRoleName}")]
        public async Task<IActionResult> Edit(int id, AddBatViewModel model)
        {
            try
            {
                await batService.UpdateAsync(id, model);
                return RedirectToAction(nameof(All));
            }
            catch(ArgumentException ae)
            {
                logger.LogError(nameof(Edit), ae.Message);
                return RedirectToAction(nameof(All)); ;
            }
            catch (Exception e)
            {
                logger.LogError(nameof(Edit), e.Message);
                ModelState.AddModelError("", $"Unexpected error occured. Please try again");
                return View(model);
            }
            
        }

        [HttpPost]
        [Authorize(Roles = $"{CoachRoleName}, {PlayerRoleName}")]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await batService.DeleteAsync(id);
                return RedirectToAction(nameof(All));
            }
            catch (ArgumentException ae)
            {
                logger.LogError(nameof(Delete), ae.Message);
                return RedirectToAction(nameof(All));
            }
            catch (Exception e)
            {
                logger.LogError(nameof(Delete), e.Message);
                return RedirectToAction(nameof(All));
            }
        }
    }
}

Baseball/Controllers/GameController.cs
using Baseball.Common.ViewModels.GameViewModels;
using Baseball.Core.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using static Baseball.Common.RoleConstants;

namespace Baseball.Controllers
{
    [Authorize]
    public class GameController : Controller
    {
        private readonly IGameService gameService;
        private readonly ITeamService teamService;
        private readonly IChampionShipService championShipService;
        private readonly ILogger logger;

        public GameController(IGameService gameService, 
            ITeamService teamService,
            IChampionShipService championShipService,
            ILogger<GameController> logger)
        {
            this.gameService = gameService;
            this.teamService = teamService;
            this.championShipService = championShipService;
            this.logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> All()
        {
            try
            {
                var teams = await gameService.GetAllAsync();
                return View(teams);
            }
            catch (Exception ex)
            {
                logger.LogError(nameof(All), ex.Message);
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpGet]
        [Authorize(Roles = $"{CoachRoleName}, {PlayerRoleName}")]
        public async Task<IActionResult> Add()
        {
            try
            {
                var model = new AddGameViewModel();
                model.Teams = await teamService.GetAllTeamNamesAsync();
                model.ChampionShips = await championShipService.GetAllChampionShipNamesAsync();

                return View(model);
            }
            catch (Exception ex)
            {
                logger.LogError(nameof(Add), ex.Message);
                return RedirectToAction(nameof(All));
            }
        }

        [HttpPost]
        [Authorize(Roles = $"{CoachRoleName}, {PlayerRoleName}")]
        public async Task<IActionResult> Add(AddGameViewModel model)
        {

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                await gameService.AddAsync(model);
                return RedirectToAction(nameof(All));
            }
            catch(ArgumentNullException ne)
            {
                logger.LogError(nameof(Add), ne.Message);
                return RedirectToAction(nameof(All));
            }
            catch (Exception e)
            {
                logger.LogError(nameof(Add), e.Message);
                return RedirectToAction(nameof(All));
            }
        }

        [HttpGet]
        [Authorize(Roles = $"{CoachRoleName}, {PlayerRoleName}")]
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var game = await gameService.GetByIdAsync(id);

                if (game == null)
                {
                    logger.LogError(nameof(Edit), "Game was not found");
                    return RedirectToAction(nameof(All));
                }

                game.Teams = await teamService.GetAllTeamNamesAsync();
                game.ChampionShips = await championShipService.GetAllChampionShipNamesAsync();

                return View(game);
            }
            catch (Exception ex)
            {
                logger.LogError(nameof(Edit), ex.Message);
                return RedirectToAction(nameof(All));
            }
        }

        [HttpPost]
        [Authorize(Roles = $"{CoachRoleName}, {PlayerRoleName}")]
        public async Task<IActionResult> Edit(int id, EditGameViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (id != model.Id)
            {
                return RedirectToAction(nameof(All));
            }

            try
            {
                await gameService.UpdateAsync(id, model);
                return RedirectToAction(nameof(All));
            }
            catch (ArgumentNullException ne)
            {
                logger.LogError(nameof(Edit), ne.Message);
                return RedirectToAction(nameof(All));
            }
            catch (Exception e)
            {
                logger.LogError(nameof(Edit), e.Message);
                return RedirectToAction(nameof(All));
            }
        }

        [HttpPost]
        [Authorize(Roles = $"{CoachRoleName}, {PlayerRoleName}")]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await gameService.DeleteAsync(id);
                return RedirectToAction(nameof(All));
            }
            catch (ArgumentNullException ne)
            {
                logger.LogError(nameof(Delete), ne.Message);
                return RedirectToAction(nameof(All));
            }
            catch (Exception e)
            {
                logger.LogError(nameof(Delete), e.Message);
                return RedirectToAction(nameof(All));
            }
        }
    }
}

Baseball/Controllers/TeamController.cs
using Baseball.Common.ViewModels.TeamViewModels;
using Baseball.Core.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using static Baseball.Common.RoleConstants;

namespace Baseball.Controllers
{
    [Authorize]
    public class TeamController : Controller
    {
        private readonly ITeamService teamService;
        private readonly ILogger logger;

        public TeamController(ITeamService teamService, ILogger<TeamController> logger)
        {
            this.teamService = teamService;
            this.logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> All()
        {
            try
            {
                var teams = await teamService.GetAllAsync();
                return View(teams);
            }
            catch (Exception e)
            {
                logger.LogError(nameof(All), e.Message);
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpGet]
        [Authorize(Roles = $"{CoachRoleName}, {PlayerRoleName}")]
        public IActionResult Add()
        {
            var model = new AddTeamModel();

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = $"{CoachRoleName}, {PlayerRoleName}")]
        public async Task<IActionResult> Add(AddTeamModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                await teamService.AddAsync(model);
                return RedirectToAction(nameof(All));
            }
            catch (Exception e)
            {
                logger.LogError(nameof(Add), e.Message);
                ModelState.AddModelError("", $"Something went wrong. Team was not added.");
                return View(model);
            };
        }

        [HttpGet]
        public async Task<IActionResult> GetDetails(int id)
        {
            try
            {
                var teamDetails = await teamService.GetDetailsAsync(id);

                if (teamDetails == null)
                {
                    ModelState.AddModelError("", "Team was not found or unexpected error occured.");
                    return RedirectToAction(nameof(All));
                }

                return View(teamDetails);
            }
            catch (Exception e)
            {
                logger.LogError(nameof(GetDetails), e.Message);
                return RedirectToAction(nameof(All));
            }
        }

        [HttpGet]
        [Authorize(Roles = $"{CoachRoleName}, {PlayerRoleName}")]
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var team = await teamService.GetByIdAsync(id);

                if (team == null)
                {
                    return RedirectToAction(nameof(All));
                }

                return View(team);
            }
            catch (Exception e)
            {
                logger.LogError(nameof(Edit), e.Message);
                return RedirectToAction(nameof(All));
            }
        }

        [HttpPost]
        [Authorize(Roles = $"{CoachRoleName}, {PlayerRoleName}")]
        public async Task<IActionResult> Edit(int id, EditTeamViewModel model)
        {
            if (id != model.Id)
            {
                return RedirectToAction(nameof(All));
            }

            try
            {
                await teamService.UpdateAsync(id, model);
                return RedirectToAction(nameof(All));
            }
            catch(ArgumentNullException ne)
            {
                logger.LogError(nameof(Edit), ne.Message);
                return RedirectToAction(nameof(All));
            }
            catch (Exception e)
            {
                logger.LogError(nameof(Edit), e.Message);
                return RedirectToAction(nameof(All));
            }
        }

        [HttpPost]
        [Authorize(Roles = $"{CoachRoleName}, {PlayerRoleName}")]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await teamService.DeleteAsync(id);
                return RedirectToAction(nameof(All));
            }
            catch (Exception e)
            {
                logger.LogError(nameof(Delete), e.Message);
                return RedirectToAction(nameof(All));
            }
        }
    }
}

Baseball/Controllers/UserController.cs
using Baseball.Common.ViewModels.UserViewModels;
using Baseball.Core.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using static Baseball.Common.RoleConstants;

namespace Baseball.Controllers
{
    [Authorize(Roles = $"{CoachRoleName}")]
    public class UserController : Controller
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly ILogger logger;

        public UserController(UserManager<IdentityUser> userManager, ILogger<UserController> logger)
        {
            this.userManager = userManager;
            this.logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GetByEmail()
        {
            var model = new GetByEmailViewModel();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> GetByEmail(GetByEmailViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                var user = await userManager.FindByEmailAsync(model.Email);

                if (user == null)
                {
                    ModelState.AddModelError("Email", $"User with email \"{model.Email}\" was not found.");

                    return View(model);
                }

                var foundbyEmailModel = new FoundByEmailViewModel()
                {
                    User = user
                };

                if ((await userManager.GetRolesAsync(user)).Any(r => r == "Player"))
                {
                    foundbyEmailModel.IsInRolePlayer = true;
                }

                return View("FoundByEmail", foundbyEmailModel);
            }
            catch (Exception e)
            {
                logger.LogError(nameof(GetByEmail), e.Message);
                ModelState.AddModelError("", $"Unexpected error occured. Please try again");
                return View(model);
            } 
        }

        [HttpGet]
        public async Task<IActionResult> GetAllUsersWithPlayerRole()
        {
            try
            {
                var players = await userManager.GetUsersInRoleAsync("Player");
                return View(players);
            }
            catch (Exception e)
            {
                logger.LogError(nameof(GetAllUsersWithPlayerRole), e.Message);
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpGet]
        public async Task<IActionResult> AddToPlayers(string id)
        {
            try
            {
                var user = await userManager.FindByIdAsync(id);

                await userManager.AddToRolesAsync(user, new string[] { "Player" });

                return RedirectToAction(nameof(GetAllUsersWithPlayerRole));
            }
            catch (Exception e)
            {
                logger.LogError(nameof(AddToPlayers), e.Message);
                return RedirectToAction(nameof(GetAllUsersWithPlayerRole));
            }
        }
    }
}

Baseball/Views/Shared/_GamePartial.cshtml
@model List<GameViewModel>

<table class="table">
    <thead class="thead-light">
        <tr>
            <th scope="col">Championship</th>
            <th scope="col">Away Team</th>
            <th scope="col">Home Team</th>
            <th scope="col">Stadium</th>
            <th scope="col">AT Runs</th>
            <th scope="col">HT Runs</th>
            <th scope="col">Innings</th>
            <th scope="col">AT Hits</th>
            <th scope="col">HT Hits</th>
            <th scope="col">AT Errors</th>
            <th scope="col">HT Errors</th>
            @if (User.IsInRole($"{CoachRoleName}") || User.IsInRole($"{PlayerRoleName}"))
            {
                <th scope="col"></th>
                <th scope="col"></th>
            }
        </tr>
    </thead>
    <tbody>
        @foreach (var game in Model)
        {
            <tr>
                <td>@game.ChampionShip</td>
                @if (game.AwayTeamRuns > game.HomeTeamRuns)
                {
                    <td><strong>@game.AwayTeamName</strong></td>
                    <td>@game.HomeTeamName</td>
                }
                else if (game.AwayTeamRuns < game.HomeTeamRuns)
                {
                    <td>@game.AwayTeamName</td>
                    <td><strong>@game.HomeTeamName</strong></td>
                }
                else
                {
                    <td>@game.AwayTeamName</td>
                    <td>@game.HomeTeamName</td>
                }
                <td>@game.Stadium</td>
                <td>@game.AwayTeamRuns</td>
                <td>@game.HomeTeamRuns</td>
                <td>@game.InningPlayed</td>
                <td>@game.AwayTeamHits</td>
                <td>@game.HomeTeamHits</td>
                <td>@game.AwayTeamErrors</td>
                <td>@game.HomeTeamErrors</td>
                @if (User.IsInRole($"{CoachRoleName}") || User.IsInRole($"{PlayerRoleName}"))
                {
                    <td>
                        <a class="fs-6 btn btn-success mb-3 p-2" asp-area="" asp-controller="Game" asp-action="Edit" asp-route-id="@game.Id">Edit</a>
                    </td>
                    <td>
                        <form class="input-group-sm" asp-controller="Game" asp-action="Delete" asp-route-id="@game.Id">
                            <input class="fs-6 btn btn-danger mb-3 p-2" type="submit" value="Delete" />
                        </form>
                    </td>
                }
            </tr>
        }
    </tbody>
</table>

Baseball/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Baseball</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Baseball.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Baseball</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.Identity?.IsAuthenticated ?? false)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Player" asp-action="All">Players</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Team" asp-action="All">Teams</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Bat" asp-action="All">Bats</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Game" asp-action="All">Games</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ChampionShip" asp-action="All">ChampionShips</a>
                            </li>
                        }
                        @if (User.IsInRole("Coach"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="GetAllUsersWithPlayerRole">Users with player role</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.UtcNow.Year - Baseball
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Baseball/Views/Shared/_PlayerPartial.cshtml
<table class="table">
    <thead class="thead-light">
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Number</th>
            <th scope="col">Position</th>
            <th scope="col">Bat</th>
            <th scope="col">Glove</th>
            <th scope="col">ThrowHand</th>
            <th scope="col">BattingAverage</th>
            <th scope="col">Team</th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var player in Model)
        {
            <tr>
                <td>@player.Name</td>
                <td>@player.Number</td>
                <td>@player.Position</td>
                <td>@player.Bat</td>
                <td>@player.Glove</td>
                <td>@player.ThrowHand</td>
                <td>@player.BattingAverage</td>
                @if (player.TeamName == null)
                {
                    if (User.IsInRole($"{CoachRoleName}") || User.IsInRole($"{PlayerRoleName}"))
                    {
                        <td>
                            <a class="fs-6 btn btn-success mb-3 p-2" asp-area="" asp-controller="Player" asp-action="AddToTeam" asp-route-id="@player.Id">Add to team</a>
                        </td>
                    }
                    else
                    {
                        <td>Free agent</td>
                    }
                }
                else
                {
                    <td>@player.TeamName</td>
                }
                @if (User.IsInRole($"{CoachRoleName}") || User.IsInRole($"{PlayerRoleName}"))
                {
                    <td>
                        <a class="fs-6 btn btn-success mb-3 p-2" asp-area="" asp-controller="Player" asp-action="Edit" asp-route-id="@player.Id">Edit</a>
                    </td>
                    <td>
                        <form class="input-group-sm" asp-controller="Player" asp-action="Delete" asp-route-id="@player.Id">
                            <input class="fs-6 btn btn-danger mb-3 p-2" type="submit" value="Delete" />
                        </form>
                    </td>
                }
            </tr>
        }
    </tbody>
</table>