Baseball/Controllers/GameController.cs
using Baseball.Common.ViewModels.GameViewModels;
using Baseball.Core.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using static Baseball.Common.RoleConstants;

namespace Baseball.Controllers
{
    [Authorize]
    public class GameController : Controller
    {
        private readonly IGameService gameService;
        private readonly ITeamService teamService;
        private readonly IChampionShipService championShipService;
        private readonly ILogger logger;

        public GameController(IGameService gameService, 
            ITeamService teamService,
            IChampionShipService championShipService,
            ILogger<GameController> logger)
        {
            this.gameService = gameService;
            this.teamService = teamService;
            this.championShipService = championShipService;
            this.logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> All()
        {
            try
            {
                var teams = await gameService.GetAllAsync();
                return View(teams);
            }
            catch (Exception ex)
            {
                logger.LogError(nameof(All), ex.Message);
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpGet]
        [Authorize(Roles = $"{CoachRoleName}, {PlayerRoleName}")]
        public async Task<IActionResult> Add()
        {
            try
            {
                var model = new AddGameViewModel();
                model.Teams = await teamService.GetAllTeamNamesAsync();
                model.ChampionShips = await championShipService.GetAllChampionShipNamesAsync();

                return View(model);
            }
            catch (Exception ex)
            {
                logger.LogError(nameof(Add), ex.Message);
                return RedirectToAction(nameof(All));
            }
        }

        [HttpPost]
        [Authorize(Roles = $"{CoachRoleName}, {PlayerRoleName}")]
        public async Task<IActionResult> Add(AddGameViewModel model)
        {

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                await gameService.AddAsync(model);
                return RedirectToAction(nameof(All));
            }
            catch(ArgumentNullException ne)
            {
                logger.LogError(nameof(Add), ne.Message);
                return RedirectToAction(nameof(All));
            }
            catch (Exception e)
            {
                logger.LogError(nameof(Add), e.Message);
                return RedirectToAction(nameof(All));
            }
        }

        [HttpGet]
        [Authorize(Roles = $"{CoachRoleName}, {PlayerRoleName}")]
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var game = await gameService.GetByIdAsync(id);

                if (game == null)
                {
                    logger.LogError(nameof(Edit), "Game was not found");
                    return RedirectToAction(nameof(All));
                }

                game.Teams = await teamService.GetAllTeamNamesAsync();
                game.ChampionShips = await championShipService.GetAllChampionShipNamesAsync();

                return View(game);
            }
            catch (Exception ex)
            {
                logger.LogError(nameof(Edit), ex.Message);
                return RedirectToAction(nameof(All));
            }
        }

        [HttpPost]
        [Authorize(Roles = $"{CoachRoleName}, {PlayerRoleName}")]
        public async Task<IActionResult> Edit(int id, EditGameViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (id != model.Id)
            {
                return RedirectToAction(nameof(All));
            }

            try
            {
                await gameService.UpdateAsync(id, model);
                return RedirectToAction(nameof(All));
            }
            catch (ArgumentNullException ne)
            {
                logger.LogError(nameof(Edit), ne.Message);
                return RedirectToAction(nameof(All));
            }
            catch (Exception e)
            {
                logger.LogError(nameof(Edit), e.Message);
                return RedirectToAction(nameof(All));
            }
        }

        [HttpPost]
        [Authorize(Roles = $"{CoachRoleName}, {PlayerRoleName}")]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await gameService.DeleteAsync(id);
                return RedirectToAction(nameof(All));
            }
            catch (ArgumentNullException ne)
            {
                logger.LogError(nameof(Delete), ne.Message);
                return RedirectToAction(nameof(All));
            }
            catch (Exception e)
            {
                logger.LogError(nameof(Delete), e.Message);
                return RedirectToAction(nameof(All));
            }
        }
    }
}

Baseball/Controllers/PlayerController.cs
using Baseball.Common.ViewModels.PlayerViewModels;
using Baseball.Common.ViewModels.TeamViewModels;
using Baseball.Core.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using static Baseball.Common.RoleConstants;

namespace Baseball.Controllers
{
    [Authorize]
    public class PlayerController : Controller
    {
        private readonly IPlayerServicece playerService;
        private readonly IBatService batService;
        private readonly ITeamService teamService;
        private readonly ILogger logger;

        public PlayerController(
            IPlayerServicece playerService,
            IBatService batService,
            ITeamService teamService,
            ILogger<PlayerController> logger)
        {
            this.playerService = playerService;
            this.batService = batService;
            this.teamService = teamService;
            this.logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> All([FromQuery]AllPlayersViewModel model)
        {
            try
            {
                var players = await playerService.GetAllAsync(model.TeamName, model.SearchText, model.Sorting);

                model.Players = players;
                model.TeamNames = await teamService.GetAllTeamNamesAsync();

                return View(model);
            }
            catch (Exception e)
            {
                logger.LogError(nameof(All), e.Message);
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpGet]
        [Authorize(Roles = $"{CoachRoleName}, {PlayerRoleName}")]
        public async Task<IActionResult> Add()
        {
            try
            {
                var model = new AddPlayerViewModel()
                {
                    Bats = await batService.GetAllAsync()
                };

                return View(model);
            }
            catch (Exception e)
            {
                logger.LogError(nameof(Add), e.Message);
                return RedirectToAction(nameof(All));
            }

        }

        [HttpPost]
        [Authorize(Roles = $"{CoachRoleName}, {PlayerRoleName}")]
        public async Task<IActionResult> Add(AddPlayerViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                await playerService.AddAsync(model);
                return RedirectToAction(nameof(All));
            }
            catch (Exception e)
            {
                logger.LogError(nameof(Add), e.Message);
                ModelState.AddModelError("", "Something went wrong. Player was not added. Please try again.");
                return View(model);
            }
        }

        [HttpGet]
        [Authorize(Roles = $"{CoachRoleName}, {PlayerRoleName}")]
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var player = await playerService.GetByIdAsync(id);

                if (player == null)
                {
                    return RedirectToAction(nameof(All));
                }

                player.Bats = await batService.GetAllAsync();

                return View(player);
            }
            catch (Exception e)
            {
                logger.LogError(nameof(Edit), e.Message);
                return RedirectToAction(nameof(All));
            }
        }

        [HttpPost]
        [Authorize(Roles = $"{CoachRoleName}, {PlayerRoleName}")]
        public async Task<IActionResult> Edit(int id, AddPlayerViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (id != model.Id)
            {
                return RedirectToAction(nameof(All));
            }

            try
            {
                await playerService.UpdateAsync(id, model);
                return RedirectToAction(nameof(All));
            }
            catch(ArgumentException ae)
            {
                logger.LogError(nameof(Edit), ae.Message);
                return RedirectToAction(nameof(All));
            }
            catch (Exception e)
            {
                logger.LogError(nameof(Edit), e.Message);
                return RedirectToAction(nameof(All));
            }
        }

        [HttpPost]
        [Authorize(Roles = $"{CoachRoleName}, {PlayerRoleName}")]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await playerService.DeleteAsync(id);
                return RedirectToAction(nameof(All));
            }
            catch(ArgumentException ae)
            {
                logger.LogError(nameof(Delete), ae.Message);
                return RedirectToAction(nameof(All));
            }
            catch (Exception e)
            {
                logger.LogError(nameof(Delete), e.Message);
                return RedirectToAction(nameof(All));
            }
        }

        [HttpGet]
        [Authorize(Roles = $"{CoachRoleName}, {PlayerRoleName}")]
        public async Task<IActionResult> AddToTeam(int id)
        {
            try
            {
                var player = await playerService.GetPlayerByIdAsync(id);

                if (player == null)
                {
                    logger.LogError(nameof(AddToTeam), $"Player with id {id} was not found.");
                    return RedirectToAction(nameof(All));
                }

                var model = new AddPlayerToTeamViewModel()
                {
                    Player = player,
                    Teams = await teamService.GetAllTeamNamesAsync()
                };

                return View(model);
            }
            catch (Exception e)
            {
                logger.LogError(nameof(AddToTeam), e.Message);
                return RedirectToAction(nameof(All));
            }
        }

        [HttpPost]
        [Authorize(Roles = $"{CoachRoleName}, {PlayerRoleName}")]
        public async Task<IActionResult> AddToTeam(int id, AddPlayerToTeamViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                await playerService.AddToTeamAsync(id, model.TeamId);
                return RedirectToAction(nameof(All));
            }
            catch(NullReferenceException ne)
            {
                logger.LogError(nameof(AddToTeam), ne.Message);
                return RedirectToAction(nameof(All));
            }
            catch (Exception e)
            {
                logger.LogError(nameof(AddToTeam), e.Message);
                return RedirectToAction(nameof(All));
            }
        }

        [HttpGet]
        [Authorize(Roles = $"{CoachRoleName}, {PlayerRoleName}")]
        public async Task<IActionResult> MakePlayerFreeAgent(int id)
        {
            try
            {
                var playersTeamId = await playerService.MakePlayerFreeAgentAsync(id);
                return RedirectToAction("GetDetails", "Team", new { id = (int)playersTeamId });
            }
            catch (NullReferenceException ne)
            {
                logger.LogError(nameof(MakePlayerFreeAgent), ne.Message);
                return RedirectToAction("All", "Team");
            }
            catch (Exception e)
            {
                logger.LogError(nameof(MakePlayerFreeAgent), e.Message);
                return RedirectToAction("All", "Team");
            }
        }
    }
}

Baseball/Views/Game/Add.cshtml
@model AddGameViewModel

@{
    ViewBag.Title = "Add Game";
}


<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form asp-action="Add" method="post">
            <div class="mb-3">
                <label asp-for="@Model.ChampionShipId" class="form-label"><strong>Championsip</strong></label>
                <select asp-for="@Model.ChampionShipId" class="form-control">
                    @foreach (var championShip in Model.ChampionShips)
                    {
                        <option value="@championShip.Id">@championShip.Name</option>
                    }
                </select>
                <span asp-validation-for="ChampionShipId" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.AwayTeamId" class="form-label"><strong>Away Team Name</strong></label>
                <select asp-for="@Model.AwayTeamId" class="form-control">
                    @foreach (var team in Model.Teams)
                    {
                        <option value="@team.Id">@team.Name</option>
                    }
                </select>
                <span asp-validation-for="AwayTeamId" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.HomeTeamId" class="form-label"><strong>Home Team Name</strong></label>
                <select asp-for="@Model.HomeTeamId" class="form-control">
                    @foreach (var team in Model.Teams)
                    {
                        <option value="@team.Id">@team.Name</option>
                    }
                </select>
                <span asp-validation-for="HomeTeamId" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Stadium" class="form-label"><strong>Stadium</strong></label>
                <input asp-for="@Model.Stadium" class="form-control" aria-required="true" />
                <span asp-validation-for="Stadium" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.InningPlayed" class="form-label"><strong>Innings played</strong></label>
                <input asp-for="@Model.InningPlayed" class="form-control" aria-required="true" />
                <span asp-validation-for="InningPlayed" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.AwayTeamRuns" class="form-label"><strong>Away Team Runs</strong></label>
                <input asp-for="@Model.AwayTeamRuns" class="form-control" aria-required="true" />
                <span asp-validation-for="AwayTeamRuns" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.HomeTeamRuns" class="form-label"><strong>Home Team Runs</strong></label>
                <input asp-for="@Model.HomeTeamRuns" class="form-control" aria-required="true" />
                <span asp-validation-for="HomeTeamRuns" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.AwayTeamHits" class="form-label"><strong>Away Team Hits</strong></label>
                <input asp-for="@Model.AwayTeamHits" class="form-control" aria-required="true" />
                <span asp-validation-for="AwayTeamHits" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.HomeTeamHits" class="form-label"><strong>Home Team Hits</strong></label>
                <input asp-for="@Model.HomeTeamHits" class="form-control" aria-required="true" />
                <span asp-validation-for="HomeTeamHits" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.AwayTeamErrors" class="form-label"><strong>Away Team Errors</strong></label>
                <input asp-for="@Model.AwayTeamErrors" class="form-control" aria-required="true" />
                <span asp-validation-for="AwayTeamErrors" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.AwayTeamErrors" class="form-label"><strong>Away Team Errors</strong></label>
                <input asp-for="@Model.AwayTeamErrors" class="form-control" aria-required="true" />
                <span asp-validation-for="AwayTeamErrors" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <input class="btn btn-primary" type="submit" value="Add" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Baseball/Views/Game/All.cshtml
@model List<GameViewModel>

@{
    ViewBag.Title = "All Games";
}

<h2 class="text-center">@ViewBag.Title</h2>
@if (User.IsInRole($"{CoachRoleName}") || User.IsInRole($"{PlayerRoleName}"))
{
    <a class="fs-6 btn btn-success mb-3 p-2" asp-area="" asp-controller="Game" asp-action="Add">Add new Game</a>
}

<partial name="_GamePartial" model="@Model" />

Baseball/Views/Game/Edit.cshtml
@model EditGameViewModel

@{
    ViewBag.Title = "Update Game";
}


<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form asp-action="Edit" method="post">
            <div class="mb-3">
                <label asp-for="@Model.ChampionShipId" class="form-label"><strong>Championsip</strong></label>
                <select asp-for="@Model.ChampionShipId" class="form-control">
                    @foreach (var championShip in Model.ChampionShips)
                    {
                        <option value="@championShip.Id">@championShip.Name</option>
                    }
                </select>
                <span asp-validation-for="ChampionShipId" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.AwayTeamId" class="form-label"><strong>Away Team Name</strong></label>
                <select asp-for="@Model.AwayTeamId" class="form-control">
                    @foreach (var team in Model.Teams)
                    {
                        <option value="@team.Id">@team.Name</option>
                    }
                </select>
                <span asp-validation-for="AwayTeamId" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.HomeTeamId" class="form-label"><strong>Home Team Name</strong></label>
                <select asp-for="@Model.HomeTeamId" class="form-control">
                    @foreach (var team in Model.Teams)
                    {
                        <option value="@team.Id">@team.Name</option>
                    }
                </select>
                <span asp-validation-for="HomeTeamId" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Stadium" class="form-label"><strong>Stadium</strong></label>
                <input asp-for="@Model.Stadium" class="form-control" aria-required="true" />
                <span asp-validation-for="Stadium" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.InningPlayed" class="form-label"><strong>Innings played</strong></label>
                <input asp-for="@Model.InningPlayed" class="form-control" aria-required="true" />
                <span asp-validation-for="InningPlayed" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.AwayTeamRuns" class="form-label"><strong>Away Team Runs</strong></label>
                <input asp-for="@Model.AwayTeamRuns" class="form-control" aria-required="true" />
                <span asp-validation-for="AwayTeamRuns" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.HomeTeamRuns" class="form-label"><strong>Home Team Runs</strong></label>
                <input asp-for="@Model.HomeTeamRuns" class="form-control" aria-required="true" />
                <span asp-validation-for="HomeTeamRuns" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.AwayTeamHits" class="form-label"><strong>Away Team Hits</strong></label>
                <input asp-for="@Model.AwayTeamHits" class="form-control" aria-required="true" />
                <span asp-validation-for="AwayTeamHits" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.HomeTeamHits" class="form-label"><strong>Home Team Hits</strong></label>
                <input asp-for="@Model.HomeTeamHits" class="form-control" aria-required="true" />
                <span asp-validation-for="HomeTeamHits" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.AwayTeamErrors" class="form-label"><strong>Away Team Errors</strong></label>
                <input asp-for="@Model.AwayTeamErrors" class="form-control" aria-required="true" />
                <span asp-validation-for="AwayTeamErrors" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.AwayTeamErrors" class="form-label"><strong>Away Team Errors</strong></label>
                <input asp-for="@Model.AwayTeamErrors" class="form-control" aria-required="true" />
                <span asp-validation-for="AwayTeamErrors" class="text-danger"></span>
            </div>
            <form class="input-group-sm" asp-controller="Player" asp-action="Edit" asp-route-bookId="@Model.Id">
                <input type="submit" value="Update" class="fs-6 btn btn-success mb-3 p-2" />
            </form>
        </form>
    </div>
</div>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}